[project]
name = "weather-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "devtools>=0.12.2",
    "httpx>=0.28.1",
    "logfire[httpx]>=3.16.0",
    "pydantic-ai>=0.2.3",
]
